import React from "react";
import { History } from "lucide-react";
import ModuleBadge from "../../../components/ModuleBadge";
import type { TransactionModel } from "../../../context/useTransactionResource";
import { formatCurrency, formatDate, formatDateTime } from "../../../utils/formatters";
import MonthTransactionsModal, { buildActualMonthBreakdown, type MonthBreakdownKind } from "../MonthTransactionsModal";
import { formatMonthLabel, type MonthlyActualSummary } from "../monthViewModel";
import type { PeriodSnapshot } from "./types";
import SnapshotMetrics from "./SnapshotMetrics";

export default function HistoryPanel({ snapshots, monthlyActuals, incomes, expenses }: { snapshots: PeriodSnapshot[]; monthlyActuals: MonthlyActualSummary[]; incomes: TransactionModel[]; expenses: TransactionModel[] }) {
  const [detail, setDetail] = React.useState<{ month: string; kind: MonthBreakdownKind; scope: "flow" | "real" } | null>(null);
  const detailRows = React.useMemo(() => detail ? buildActualMonthBreakdown(detail.month, detail.kind, detail.kind === "income" ? incomes : expenses, detail.scope === "flow") : [], [detail, expenses, incomes]);
  return <div className="space-y-3">
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-4"><h2 className="text-lg font-bold text-slate-900">Miesięczne wykonanie</h2><p className="text-sm text-slate-500">Przepływy pokazują wszystkie wykonane operacje. Realne wartości nie liczą transferów własnych ani operacji ręcznie pominiętych.</p></div>{monthlyActuals.length ? <div className="overflow-auto"><table className="w-full min-w-[920px] text-sm"><thead className="bg-slate-100 text-left text-slate-700"><tr><th className="px-4 py-3">Miesiąc</th><th className="px-4 py-3 text-right">Przepływy · wpływy</th><th className="px-4 py-3 text-right">Przepływy · wypływy</th><th className="px-4 py-3 text-right">Realne przychody</th><th className="px-4 py-3 text-right">Realne wydatki</th><th className="px-4 py-3 text-right">Wynik</th></tr></thead><tbody>{monthlyActuals.map((row) => <tr key={row.month} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold">{formatMonthLabel(row.month)}</td><td className="px-4 py-3 text-right font-semibold text-emerald-700"><button type="button" className="font-semibold underline-offset-2 hover:underline" onClick={() => setDetail({ month: row.month, kind: "income", scope: "flow" })}>{formatCurrency(row.allIncome)}</button></td><td className="px-4 py-3 text-right font-semibold text-red-700"><button type="button" className="font-semibold underline-offset-2 hover:underline" onClick={() => setDetail({ month: row.month, kind: "expense", scope: "flow" })}>{formatCurrency(row.allExpenses)}</button></td><td className="px-4 py-3 text-right font-semibold text-emerald-700"><button type="button" className="font-semibold underline-offset-2 hover:underline" onClick={() => setDetail({ month: row.month, kind: "income", scope: "real" })}>{formatCurrency(row.income)}</button></td><td className="px-4 py-3 text-right font-semibold text-red-700"><button type="button" className="font-semibold underline-offset-2 hover:underline" onClick={() => setDetail({ month: row.month, kind: "expense", scope: "real" })}>{formatCurrency(row.expenses)}</button></td><td className={`px-4 py-3 text-right font-bold ${row.net < 0 ? "text-red-700" : "text-slate-900"}`}>{formatCurrency(row.net)}</td></tr>)}</tbody></table></div> : <p className="p-5 text-sm text-slate-500">Brak wykonanych transakcji dla wybranych filtrów.</p>}</section>
    <div><h2 className="text-lg font-bold text-slate-900">Zapisane stany finansowe</h2><p className="text-sm text-slate-500">Ręcznie zapisane stany okresów wypłatowych. Wartości odpowiadają chwili zapisu.</p></div>
    {!snapshots.length ? <section className="rounded-xl border border-slate-200 bg-white p-6 text-center shadow-sm"><History className="mx-auto text-slate-400" size={28} aria-hidden="true" /><p className="mt-2 text-sm text-slate-500">Nie zapisano jeszcze żadnego podsumowania okresu. Możesz zrobić to ręcznie w zakładce Okres.</p></section> : snapshots.map((snapshot, index) => {
      const older = snapshots[index + 1];
      const floorSecured = snapshot.real_liquidity >= snapshot.financial_floor;
      return <article key={snapshot.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-bold text-slate-900">{formatDate(`${snapshot.period_start}T12:00:00`)} – {formatDate(`${snapshot.period_end}T12:00:00`)}</h3><p className="mt-0.5 text-xs text-slate-500">Stan zapisany: {formatDateTime(snapshot.captured_at)}</p></div><ModuleBadge size="sm" tone={floorSecured ? "success" : "danger"}>{floorSecured ? "Podłoga zabezpieczona" : "Poniżej finansowej podłogi"}</ModuleBadge></div><SnapshotMetrics snapshot={snapshot} older={older} className="mt-4" /></article>;
    })}
    {detail && <MonthTransactionsModal open month={detail.month} kind={detail.kind} mode="actual" rows={detailRows} titleOverride={detail.scope === "flow" ? `Przepływy · ${detail.kind === "income" ? "wpływy" : "wypływy"} - ${formatMonthLabel(detail.month)}` : undefined} onClose={() => setDetail(null)} />}
  </div>;
}
